// create course constants
export const GET_OPPOPRTUNITY = "GET_OPPOPRTUNITY";
export const GET_OPPOPRTUNITY_SUCCESS = "GET_OPPOPRTUNITY_SUCCESS";
export const GET_OPPOPRTUNITY_FAILED = "GET_OPPOPRTUNITY_FAILED";


export const SEARCH_OPPOPRTUNITY = "SEARCH_OPPOPRTUNITY";
export const SEARCH_OPPOPRTUNITY_SUCCESS = "SEARCH_OPPOPRTUNITY_SUCCESS";
export const SEARCH_OPPOPRTUNITY_FAILED = "SEARCH_OPPOPRTUNITY_FAILED";


// create course constants
export const CREATE_OPPOPRTUNITY = "CREATE_OPPOPRTUNITY";
export const CREATE_OPPOPRTUNITY_SUCCESS = "CREATE_OPPOPRTUNITY_SUCCESS";
export const CREATE_OPPOPRTUNITY_FAILED = "CREATE_OPPOPRTUNITY_FAILED";

// create OPPOPRTUNITY constants
export const UPDATE_OPPOPRTUNITY = "UPDATE_OPPOPRTUNITY";
export const UPDATE_OPPOPRTUNITY_SUCCESS = "UPDATE_OPPOPRTUNITY_SUCCESS";
export const UPDATE_OPPOPRTUNITY_FAILED = "UPDATE_OPPOPRTUNITY_FAILED";

// delete OPPOPRTUNITY constants
export const DELETE_OPPOPRTUNITY = "DELETE_OPPOPRTUNITY";
export const DELETE_OPPOPRTUNITY_SUCCESS = "DELETE_OPPOPRTUNITY_SUCCESS";
export const DELETE_OPPOPRTUNITY_FAILED = "DELETE_OPPOPRTUNITY_FAILED";

export const CLEAN_UP = "CLEAN_UP";
